from . import tools
import numpy as np

class Tape5Generator():
    def __init__(self, lblinst):
        self.configuration = lblinst.configuration
        pass

    @property
    def tape5(self):
        # RECORD 1.1 & RECORD 1.2
        tape5 = self.record_1 + '\n' + self.record_12

        # RECORD 1.3
        if self.configuration.molecular_spectral_lines._lineshape_no > 0: # TODO  (required if IHIRAC > 0; IAERSL > 0; IEMIT = 1; IATM = 1; or ILAS > 0; otherwise omit)
            tape5 += '\n' + self.record_13
            # RECORD 1.3a & 1.3b # which molecuels (a) and concentrations (b)
            if 1:  # TODO (required if NMOL_SCAL > 0;  otherwise omit)
                tape5 += '\n' + self.record_13a
                tape5 += self.record_13b #requriered if 13a is present
        # TODO 0 RECORD 1.4    (required if IEMIT = 1, or both IEMIT=2 and IOTFLG=2; otherwise omit)
        # TODO 0 RECORD 1.5   (required for Analytic Jacobian calculation: IEMIT=3 and IMRG=40,41,42 or 43)
        # TODO 0 RECORD 1.6a    (required if IMRG = 35-36, 40-41, 45-46; otherwise omit)
        # TODO 0 Layer Inputs - RECORD 2.1... these records applicable only if LBLATM not selected (IATM=0) 

        # RECORD 3.1 Atmospheric Profile
        if 1: # TODO these records applicable if LBLATM selected (IATM=1) 
            tape5 += '\n' + self.record_31

            # RECORD 3.2
            if 1: # TODO SLANT PATH (ITYPE = 2,3) (MODEL = 0-6) 
                tape5 += '\n' + self.record_32

            # RECORD 3.3a 
            # TODO 0  RECORD 3.3A        For IBMAX  = 0 (from RECORD 3.1)
            if 1:    # TODO For IBMAX > 0  (from RECORD 3.1)
                tape5 += self.record_33b 

        # TODO 0 User Defined Atmospheric Profile (MODEL = 0) RECORD 3.4
        # TODO 0 RECORD 3.5
        # TODO  RECORD 3.6.1 ... 3.6.N
        # TODO  RECORD 3.7
        # TODO  RECORD 3.7.1
        # TODO  RECORD 3.8
        # TODO  RECORD 3.8.1
        # TODO  RECORD 3.8.2 ... 3.8.N
        # TODO  RECORD 3.9
        # TODO  RECORD 3.9.1
        # TODO  RECORD 3.9.2
        # TODO  RECORD 3.9.3
        # TODO  RECORD 3.9.4
        # TODO  RECORD 4 ... Aerosols
        # TODO  RECORD 5 ... Laser
        # TODO  RECORD 6 ... ???
        # TODO  RECORD 7 ... filter related
        # TODO  RECORD 8 ... Scan function
        # TODO  RECORD 9 ... Interpolation
        # TODO  RECORD 10 ... FFTSCN
        # TODO  RECORD 11 ... again filter related? filter function?
        # TODO  RECORD 12 ... PLTLBL

        # END OF TAPE5
        tape5 += '\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'

        return tape5
    
    @property
    def record_1(self):
        # RECORD 1.1
        record11 = '$ TAPE5 LBLRTM INPUT file generated by tapefive'
        return record11
    
    @property
    def record_12(self):
        #RECORD 1.2
        # IHIRAC
        vp = ((f'HI={self.configuration.molecular_spectral_lines._lineshape_no}',5),
            ('F4=1', 10),#TODO configure
            ('CN=5', 15),#TODO configure
            ('AE=0', 20),
            ('EM=0', 25),
            ('SC=0', 30),
            ('FI=0', 35),
            ('PL=0', 40),
            ('TS=0', 45),
            ('AM=1', 50),#TODO configure
            ('MG=0', 55),
            ('LA=0', 60),
            ('OD=0', 65),
            ('XS=0', 70),
            ('00', 75),
            ('00', 80),
            ('', 85),
            ('', 90),
            )
        values, positions = zip(*vp)
        record12 = tools.place_in_string(values, positions)
        return record12
    
    @property
    def record_13(self):
        #RECORD 1.3
        # if self.configuration.molecular_spectral_lines._lineshape_no > 0:
        V1 = self.configuration.spectral_grid.fmin
        V1 = f'{V1:10.3E}'
        V2 = self.configuration.spectral_grid.fmax
        V2 = f'{V2:10.3E}'
        SAMPLE = float(4) # TODO configure
        SAMPLE = f'{SAMPLE:10.3E}'
        DVSET = float(0) # TODO configure
        DVSET = f'{DVSET:10.3E}'
        ALFAL0 = float(0.04)
        ALFAL0 = f'{ALFAL0:10.3E}'
        AVMASS = float(36) #TODO MAKE SURE THIS 
        AVMASS = f'{AVMASS:10.3E}'
        DPTMIN = float(0)
        DPTMIN = f'{DPTMIN:10.3E}'        
        DPTFAC = float(0)
        DPTFAC = f'{DPTFAC:10.3E}'
        ILNFLG = int(0)
        DVOUT = float(0)
        DVOUT = f'{DVOUT:10.3E}'
        NMOL_SCAL = int(39) # TODO configure
        
        vp = ((f'{V1}',10),
            (f'{V2}',20),
            (f'{SAMPLE}',30),
            (f'{DVSET}',40),
            (f'{ALFAL0}',50),
            (f'{AVMASS}',60),
            (f'{DPTMIN}',70),
            (f'{DPTFAC}',80),
            (f'{ILNFLG}',85),
            (f'{DVOUT}',100),
            (f'{NMOL_SCAL}',105),
            # (f'',),
            # (f'',),
            # (f'',),
            )
        values, positions = zip(*vp)
        record13 = tools.place_in_string(values, positions)
        # record12 += '\n' + record13
        return record13
    
    @property
    def record_13a(self):
        #RECORD 1.3a
        # if self.configuration.molecular_spectral_lines._lineshape_no > 0:
        H2O = 'P' # TODO configure
        CO2 = 0
        O3 = 0
        N2O = 0
        CO = 0
        CH4 = 0
        O2 = 0
        NO = 0
        SO2 = 0
        NO2 = 0
        NH3 = 0
        HNO3 = 0
        OH = 0
        HF = 0
        HCL = 0
        HBR = 0
        HI = 0
        CLO = 0
        OCS = 0
        H2CO = 0
        HOCL = 0
        N2 = 0
        HCN = 0
        CH3CL = 0
        H2O2 = 0
        C2H2 = 0
        C2H6 = 0
        PH3 = 0
        COF2 = 0
        SF6 = 0
        H2S = 0
        HCOOH = 0
        HO2 = 0
        O = 0
        CLONO2 = 0
        NOp = 0
        HOBR = 0
        C2H4 = 0
        CH3OH = 0
        record13a = f'{H2O}{CO2}{O3}{N2O}{CO}{CH4}{O2}{NO}{SO2}{NO2}{NH3}{HNO3}{OH}{HF}{HCL}{HBR}{HI}{CLO}{OCS}{H2CO}{HOCL}{N2}{HCN}{CH3CL}{H2O2}{C2H2}{C2H6}{PH3}{COF2}{SF6}{H2S}{HCOOH}{HO2}{O}{CLONO2}{NOp}{HOBR}{C2H4}{CH3OH}'
                # record12 += '\n' + record13a
        # tape5 = '\n'.join([record11, record12])
        return record13a
    
    @property
    def record_13b(self):
        #RECORD 1.3b
        # concentrations for each molecule
        # if self.configuration.molecular_spectral_lines._lineshape_no > 0:
        H2O = 0.5
        CO2 = 0
        O3 = 0
        N2O = 0
        CO = 0
        CH4 = 0
        O2 = 0
        NO = 0
        SO2 = 0
        NO2 = 0
        NH3 = 0
        HNO3 = 0
        OH = 0
        HF = 0
        HCL = 0
        HBR = 0
        HI = 0
        CLO = 0
        OCS = 0
        H2CO = 0
        HOCL = 0
        N2 = 0
        HCN = 0
        CH3CL = 0
        H2O2 = 0
        C2H2 = 0
        C2H6 = 0
        PH3 = 0
        COF2 = 0
        SF6 = 0
        H2S = 0
        HCOOH = 0
        HO2 = 0
        O = 0
        CLONO2 = 0
        NOp = 0
        HOBR = 0
        C2H4 = 0
        CH3OH = 0


        chunk_size = 8
        
        mollist = [H2O,CO2,O3,N2O,CO,CH4,O2,NO,SO2,NO2,NH3,HNO3,OH,HF,HCL,HBR,HI,CLO,OCS,H2CO,HOCL,N2,HCN,CH3CL,H2O2,C2H2,C2H6,PH3,COF2,SF6,H2S,HCOOH,HO2,O,CLONO2,NOp,HOBR,C2H4,CH3OH]
        mollist = [f"{m:15.7E}" for m in mollist]
        wrapped = [mollist[i:i + chunk_size] for i in range(0, len(mollist), chunk_size)]
        txt = ''
        for l in wrapped:
            txt += '\n'+''.join(l)
        record13b = txt
        return record13b

    @property
    def record_31(self):
        # RECORD 3.1
        vd =   {'MODEL' : 2, #TODO configure
                'ITYPE' : 2, #TODO configure
                'IBMAX' : 19,#TODO configure
                'ZERO' : 0,
                'NOPRNT' : 0,
                'NMOL' : '',
                'IPUNCH' : '',
                'IFXTYP' : '',
                'MUNITS' : '',
                'RE' : '',
                'HSPACE' : '',
                'VBAR' : '',
                'REF_LAT' : '',
                }

        var = "MODEL,  ITYPE, IBMAX,    ZERO,  NOPRNT,  NMOL, IPUNCH, IFXTYP,   MUNITS,    RE, HSPACE,  VBAR,      REF_LAT" #copied from documentation
        var = [u.strip() for u in var.split(',')]
        val = [vd[v] for v in var]
        pos = "5,     10,    15,      20,      25,    30,     35,  36-37,    39-40, 41-50,  51-60, 61-70,        81-90" #copied from documentation
        pos = [int(k.strip().split('-')[-1]) for k in pos.split(',')]
        record31 = tools.place_in_string(val, pos)
        return record31
    
    @property
    def record_32(self):
        vd =   {'H1' : f"{0:10.3E}",
        'H2' : f"{100:10.3E}",
        'ANGLE' : f"{0:10.3E}",
        'RANGE' : '',
        'BETA' : '',
        'LEN' : '',
        'HOBS' : '',
                }

        var = "H1,    H2,   ANGLE,   RANGE,   BETA,   LEN,     HOBS" #copied from documentation
        var = [u.strip() for u in var.split(',')]
        val = [vd[v] for v in var]
        pos = "1-10, 11-20,   21-30,   31-40,  41-50, 51-55,    61-70" #copied from documentation
        pos = [int(k.strip().split('-')[-1]) for k in pos.split(',')]

        record32 =  tools.place_in_string(val, pos)
        return record32

    @property
    def record_33b(self):
        # RECORD 3.3b
        # standard atmosphere layers in km
        layers = np.array([0.0,
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                6.0,
                7.0,
                8.0,
                9.0,
                10.0,
                11.0,
                20.0,
                30.0,
                50.0,
                70.0,
                80.0,
                90.0,
                100.0])


        chunk_size = 8

        layers = [f"{m:10.3E}" for m in layers]
        wrapped = [layers[i:i + chunk_size] for i in range(0, len(layers), chunk_size)]
        txt = ''
        for l in wrapped:
            txt += '\n'+''.join(l)
        record33b = txt
        return record33b




        